#define SOKOL_IMPL
#define SOKOL_NO_ENTRY
#define SOKOL_NO_DEPRECATED
#define SOKOL_TRACE_HOOKS
#include <sokol_app.h>
#include <sokol_audio.h>
#include <sokol_gfx.h>
#include <sokol_gl.h>
#include <sokol_shape.h>
#include <sokol_debugtext.h>
#include <sokol_time.h>
